### ISSUE TITLE
also provide a method for getting explanations for single classes

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#11]
see http://owlapi.sourceforge.net/javadoc/com/clarkparsia/owlapi/explanation/ExplanationGenerator.html

**Comment by ramyadirsumilli** [comment]
I have added the new method.. 
Please check the documentation for details.. 

http://localhost:3000/unsatExplanations/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/CheeseyVegetableTopping

**Comment by tillmo** [comment]
OK, I have tried it. The documentation contains a typo: `profileName` is used as method name in the URL.

I get the following output:
```
[["<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping>","[[SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping>), SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>), DisjointClasses(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>)]]"]]
```
I expect to get an output of form
```
{"classname":[axiom1,axiom2,...]}
```
Your output uses an array of arrays (why?), a simple array would suffice. And since we expect the explanation for only one class only, it could be even a structured object. Moreover, in your output, all axioms are joined into one big string starting with "[[". Instead, there should be an array of axioms.

**Comment by ramyadirsumilli** [comment]
I have sorted the output accordingly.

**Comment by tillmo** [comment]
OK, but the second problem is still there: all axioms are joined into one big string starting with "[[". Instead, there should be an array of axioms. That is, instead of `"[[SubClassOf(<http://www...` it should be `["SubClassOf(<http://www...`

**Comment by ramyadirsumilli** [comment]
resolved the issue

**Comment by tillmo** [comment]
Now it is `"[SubClassOf(<http://www...`. But it should be `["SubClassOf(<http://www...`

**Comment by ramyadirsumilli** [comment]
Can you please check this method now ?

**Comment by tillmo** [comment]
works!
