### ISSUE TITLE
provide a method for conversion among the different OWL syntaxes

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#12]
i.e. an OWL ontology is read in from some URL and then output in the specified syntax

**Comment by tillmo** [comment]
it also would be nice if one is able to choose the output format for OWL ontologies generated by the hierarchy and modularity commands.

**Comment by ramyadirsumilli** [comment]
I have implemented the new method for conversion

http://localhost:3000/OntoConversion/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/owlxml

owlxml, rdfowl and manowl are the formats possible. 

please try this post method.  I have also updated the documentation.

Also I will soon update the Hierarchy and modularity to accept input format.

**Comment by tillmo** [comment]
owlxml and manowl work, rdfowl does not work.
Where do the terms owlxml, rdfowl and manowl come from? The naming is not so systematic: the "owl" is sometimes a prefix, sometimes a suffix.

**Comment by ramyadirsumilli** [comment]
Sorry. I spelled it wrong. it is rdfxml.
I have used the names from the short of the method names for conversion

 * owlxml - OWL/XML Ontology Format
 * manowl - Manchester OWL Syntax Ontology Format
 * rdfxml - RDF/XML Ontology Format

Also check the Modularity and Inferred Ontology with the same formats. 
I have updated further details in README.md

http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/hasSpiciness/owlxml

http://localhost:3000/inferredOntology/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/rdfxml

**Comment by tillmo** [comment]
good, works!
