### ISSUE TITLE
use a newer version of the OWL API

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#14]
rest_owl_api uses OWL API version 1.3.8.1099, at least that is the version that is marked in generated owl files:
```
<!-- Generated by the OWL API (version 1.3.8.1099) http://owlapi.sourceforge.net -->
```
When generating a file with Protégé, I get
```
<!-- Generated by the OWL API (version 3.0.0.1450) http://owlapi.sourceforge.net -->
```

**Comment by ramyadirsumilli** [comment]
I am using OWL API version 3.5.0
Would there be any other influence of version ?

**Comment by tillmo** [comment]
We should use the latest version, because it has most bug fixes.
What do get as the last line of
```
http://localhost:3000/OntoConversion/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/xmlowl
```

**Comment by tillmo** [comment]
`lib/owlapi-api.jar` contains an old version of the OWL API. Could this be the problem?

**Comment by ramyadirsumilli** [comment]
resolved the issue, 
the problem was `lib/HermiT.jar` which was based old OWL API version.

**Comment by tillmo** [comment]
strange, why is hermit involved here? But it works now.
