### ISSUE TITLE
module extraction always delivers the whole ontology

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#15]
see e.g. http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Fsandbox%2Fsmall_ontology.omn/A/owlman
You get the whole ontology. However, the module should only contain class A, and not classes B and C (they are completely unrelated to class A).

**Comment by ramyadirsumilli** [comment]
Sorry. 
That was a return statement error. I have corrected it. 
Please verify now.

**Comment by tillmo** [comment]
hm, now http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Fsandbox%2Fsmall_ontology.omn/A/owlman returns the empty ontology. But the result should contain class A.

**Comment by tillmo** [comment]
the problem is only the correct prefixing of the classes (A in the example).

**Comment by ramyadirsumilli** [comment]
I did some changes. 
But was unable to use NamespaceOWLOntology. 
It is not available in  new versions of  OWL API. 
There is a replacement, using prefixOWLOntologyFormat and getPrefixName2PrefixMap(), but it returns the complete prefix.
I will try to work on it once again .

**Comment by tillmo** [comment]
works now!
