### ISSUE TITLE
output json in a uniform style

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#5]
* `exploreClasses` outputs a list that is not a json array
* `descendants` outputs an array of form `[{"CoberturaDeQueijoComVegetais":"CoberturaDeQueijoDeCabra"},...`
* `hierarchy` outputs an array of form `[["Root","http://www.w3.org/2002/07/owl#Thing"],...`
* `petInstances`outputs an array of form `["http://www.co-ode.org/ontologies/pizza/pizza.owl#France:Pais",...]` (this is clearly undesirable, because the individual and its class are combined into one string)

Is there a reason to use these different formats? If not, the output should be uniform.

**Comment by ramyadirsumilli** [comment]
Please verify the formats. 
And I am still working on the number of descendants. 
thank you!

**Comment by tillmo** [comment]
Could you please specify what has changed? For example, `petInstances` still produces the same (undesirable) output.

**Comment by ramyadirsumilli** [comment]
Please try to work with PetInstances once again with an ontology input which has ObjectPropertyValues

**Comment by tillmo** [comment]
With
```
curl  http://localhost:3000/petInstances/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl
```
I get an empty output. However, there are individuals in this ontology, e.g. `France` which is an instance of `Country`.

**Comment by ramyadirsumilli** [comment]
Could you please try working with it once again.

**Comment by tillmo** [comment]
works!
