### ISSUE TITLE
output OWL ontologies in a uniform style

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#6]
* `inferredOntology` outputs XML syntax
* `modularity` outputs functional syntax

Is there a reason to use these different formats? If not, the output should be uniform.

**Comment by ramyadirsumilli** [comment]
Please check the updated modularity. Previously i have generated modular axioms instead of module ontology.

**Comment by tillmo** [comment]
yes, that's good.
