### ISSUE TITLE
modularity needs a second parameter, the signature

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#7]

**Comment by ramyadirsumilli** [comment]
Please recheck with new URI format: 
http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/hasSpiciness

**Comment by tillmo** [comment]
OK, but how do I submit a signature consisting of more than one symbol?

**Comment by ramyadirsumilli** [comment]
could you please state an example of how would a signature with more than one symbol be ?

**Comment by tillmo** [comment]
e.g.
http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/hasSpiciness,Mushroom

**Comment by ramyadirsumilli** [comment]
Please check now with:
http://localhost:3000/modularity/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl/hasSpiciness,Mushroom/owlxml

However, now the output is set of OWLOntology modules. 
Please let me know if I have to merge these ontologies into single ontology.

**Comment by tillmo** [comment]
No, the OWL API should output a single ontology, and you need to return that single ontology. We neither need a set of ontologies, nor some merge of a such a set.

**Comment by ramyadirsumilli** [comment]
Could you please re-verify now.

**Comment by tillmo** [comment]
works
