### ISSUE TITLE
improve output of checkProfiles

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#8]
Currently, the output is of form
```
[{"OWL2":[null]},
{"DL":[null]},
{"EL":[["FunctionalObjectProperty axioms are not allowed in profile. FunctionalObjectProperty(<http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf>) [in ontology OntologyID(OntologyIRI(<http://www.co-ode.org/ontologies/pizza/pizza.owl>))]"],...
```
* why is the error array for OWL and DL `[null]` and not just `[]`?
* why does the error arrray of form `[["error1"],["error2"],...]`? Wouldn't `["error1","error2",...]`be neater?
* An error should not be represented by just a string, but by a more complex object consisting of the error message and the place where the error has been found

**Comment by tillmo** [comment]
the same comment applies to `verifyProfile`

**Comment by ramyadirsumilli** [comment]
I have formatted the result. 
Please verify now.

**Comment by tillmo** [comment]
better now.
