### ISSUE TITLE
unclear output for explanation

### ISSUE THREAD

**Issue by tillmo** [ramyadirsumilli/rest_owl_api#9]
http://localhost:3000/explanations/http%3A%2F%2Fontohub.org%2Ftones%2Fwww.co-ode.org%2Fpizza.owl gives
```
[{"Satifiable":["<http://www.co-ode.org/ontologies/pizza/pizza.owl#Mushroom>", ... ]},
{"Unsatifiable":["<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping>",
"<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping>",
"SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping>)",
"SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>)",
"DisjointClasses(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>)",
"<http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream>",
"<http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream>",
"ObjectPropertyDomain(<http://www.co-ode.org/ontologies/pizza/pizza.owl#hasTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#Pizza>)",
"SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream> ObjectSomeValuesFrom(<http://www.co-ode.org/ontologies/pizza/pizza.owl#hasTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#FruitTopping>))",
"DisjointClasses(<http://www.co-ode.org/ontologies/pizza/pizza.owl#IceCream> <http://www.co-ode.org/ontologies/pizza/pizza.owl#Pizza>)",...
{"Inconsistent_Ontology":[]}]
```
* the array for `"Unsatifiable"` does not only contain classes, but also axioms. What does this mean?
* where are the explanations for the unsatisfiability of the unsatisfiable classes?

**Comment by ramyadirsumilli** [comment]
* The "Unsatisfiable" here has a format of
```
{"Unsatisfiable": ["Unsatisfiable Class name" , "Explanations with Axioms that lead to unsatisfiablitiy", "Unsatisfiable Class name", "Explanations with Axioms that lead to unsatisfiablitiy", .... ] 
}
```

* Therefore in the above Unsatisfiable block, it shows that ``` "<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping>" ``` is unsatisfiable, as ``` "SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping>)" ``` and ``` "SubClassOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseyVegetableTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>)" ``` but ``` "DisjointClasses(<http://www.co-ode.org/ontologies/pizza/pizza.owl#CheeseTopping> <http://www.co-ode.org/ontologies/pizza/pizza.owl#VegetableTopping>)" ``` both the classes are disjoint. 

* Please note that the format of Explanations is automatically generated  by ExplanationGenerator and hence I did not make any changes in it. 
* But, if required I can change the output format to 
```
{"Unsatisfiable": [ ["Unsatisfiable Class name" , "Explanations with Axioms that lead to unsatisfiablitiy"], ["Unsatisfiable Class name", "Explanations with Axioms that lead to unsatisfiablitiy"], [ .... ] 
}
```
 that is, I can divide each Unsatisfiable class and its explanations into a special block. But I think the output is already formatted. Adding additional block is only making it more human-readable.

**Comment by tillmo** [comment]
Human readability is not the goal here. The goal is an API that produces machine-readable output.

The problem is that currently the output does not match your specification. The output is an array of classes mixed with axioms. It is not clear which axiom belongs to which class.

Moreover, in your specification of the output, `"Explanations with Axioms that lead to unsatisfiablitiy"` should not be a string, but an array of strings. After all, there can be several axioms, so we need an array for them.

**Comment by ramyadirsumilli** [comment]
I have sorted the output accordingly.

**Comment by tillmo** [comment]
good. Now one last point. For an inconsistent ontology like `http://localhost:3000/explanations/http%3A%2F%2Fontohub.org%2Fsandbox%2Finconsistent.omn`, I correctly get that all classes are inconsistent, but I also get `{"Inconsistent_Ontology":{}}`. If the purpose of the `Inconsistent_Ontology` field is to indicate inconsistency of the ontology, I would expect some output here for an inconsistent ontology.

**Comment by ramyadirsumilli** [comment]
Removed ` ` `Inconsistent_Ontology` ` `. 
Now it returns ` ` `Satisfiable {} ` ` ` and ` ` `Unsatisfiable {}` ` `

**Comment by tillmo** [comment]
works!
